classDiagram
    class Game {
        -Board board
        -Party party
        -List~Hero~ heroes
        -List~Monster~ monsters
        -List~Item~ items
        -Input input
        -Output output
        +start()
        +gameLoop()
    }

    class Board {
        -Tile[][] grid
        -int width
        -int height
        +initializeBoard()
        +moveEntity()
        +printBoard()
    }

    class Tile {
        <<Abstract>>
        -Entity entity
        -int x
        -int y
        +isAccessible()
    }
    class CommonTile
    class MarketTile
    class InaccessibleTile

    Tile <|-- CommonTile
    Tile <|-- MarketTile
    Tile <|-- InaccessibleTile

    class Entity {
        <<Abstract>>
        #String name
        #int level
        #int hp
        #int x
        #int y
        +takeDamage()
        +isAlive()
    }

    class Hero {
        <<Abstract>>
        #int mana
        #int strength
        #int agility
        #int dexterity
        #int money
        #int experience
        #List~Item~ inventory
        #Weapon mainHandWeapon
        #Armor equippedArmor
        +levelUp()
        +equipMainHand()
        +equipArmor()
    }
    class Warrior
    class Sorcerer
    class Paladin

    Entity <|-- Hero
    Hero <|-- Warrior
    Hero <|-- Sorcerer
    Hero <|-- Paladin

    class Monster {
        <<Abstract>>
        #int damage
        #int defense
        #int dodgeChance
    }
    class Dragon
    class Exoskeleton
    class Spirit

    Entity <|-- Monster
    Monster <|-- Dragon
    Monster <|-- Exoskeleton
    Monster <|-- Spirit

    class Party {
        -List~Hero~ heroes
        +addHero()
        +getHeroes()
    }

    class Item {
        <<Abstract>>
        #String name
        #int cost
        #int requiredLevel
    }
    class Weapon {
        -int damage
        -int requiredHands
    }
    class Armor {
        -int damageReduction
    }
    class Potion {
        -int attributeIncrease
        -String attributeAffected
    }
    class Spell {
        <<Abstract>>
        -int damage
        -int manaCost
    }
    class FireSpell
    class IceSpell
    class LightningSpell

    Item <|-- Weapon
    Item <|-- Armor
    Item <|-- Potion
    Item <|-- Spell
    Spell <|-- FireSpell
    Spell <|-- IceSpell
    Spell <|-- LightningSpell

    class Battle {
        -Party party
        -List~Monster~ monsters
        +startBattle()
        +heroTurn()
        +monsterTurn()
    }

    Game --> Board
    Game --> Party
    Game ..> Battle
    Board *-- Tile
    Tile o-- Entity
    Party o-- Hero
    Hero o-- Item
    Battle --> Party
    Battle --> Monster
